plugins {
    id "idea"
    id "maven-publish"
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.1.7" // Required for NeoGradle
}

JavaLanguageVersion JAVA_VERSION = JavaLanguageVersion.of(java_version)
String JAVA_VM_VERSION = System.getProperty("java.vm.version")
String JAVA_VM_VENDOR = System.getProperty("java.vm.vendor")
Set<String> FILES_TO_EXPAND = ["pack.mcmeta", "fabric.mod.json", "META-INF/mods.toml", "META-INF/neoforge.mods.toml"]

println "$mod_name: $mod_version"
println "Java: $JAVA_VM_VERSION ($JAVA_VM_VENDOR)"
println "Minecraft: $minecraft_version"

subprojects {
    apply plugin: "java"
    apply plugin: "idea"
    apply plugin: "maven-publish"

    ext {
        platform_name = project.name.toLowerCase()
        common_mixin_config = "${mod_id}.mixins.json"
        platform_mixin_config = "${mod_id}.${platform_name}.mixins.json"
        mixin_refmap = "${mod_id}.refmap.json"
        datagen_package_path = datagen_package.replaceAll(/\./, "/")
        datagen_handler_path = datagen_handler.replaceAll(/\./, "/") + ".class"
        access_widener_path = "src/main/resources/${mod_id}.accesswidener"
        access_transformer_path = "src/main/resources/META-INF/accesstransformer.cfg"
    }

    version = minecraft_version + "-" + mod_version
    group = mod_group_id

    base {
        archivesName = "$mod_archives_base_name-$platform_name"
    }

    java {
        sourceCompatibility = JAVA_VERSION
        targetCompatibility = JAVA_VERSION
        toolchain.languageVersion.set(JAVA_VERSION)
        withSourcesJar()
        withJavadocJar()
    }

    repositories {
        mavenCentral()

        maven {
            name = "SpongePowered"
            url = "https://repo.spongepowered.org/repository/maven-public"
        }

        maven {
            name = "Forge"
            url = "https://maven.minecraftforge.net"
        }
    }

    jar {
        manifest {
            attributes "Specification-Title": mod_name
            attributes "Specification-Version": mod_version
            attributes "Specification-Vendor": mod_author
            attributes "Implementation-Title": project.name
            attributes "Implementation-Version": mod_version
            attributes "Implementation-Vendor": mod_author
            attributes "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
            attributes "Timestamp": System.currentTimeMillis()
            attributes "Built-On-Java": "$JAVA_VM_VERSION ($JAVA_VM_VENDOR)"
            attributes "Built-On-Minecraft": minecraft_version
        }

        from "LICENSE"
        exclude datagen_package_path, datagen_handler_path
    }

    processResources {
        Properties properties = new Properties()

        file("${rootProject.projectDir}/gradle.properties").withInputStream {
            properties.load(it)
        }

        inputs.properties(properties)

        filesMatching(FILES_TO_EXPAND) {
            expand properties
        }
    }

    // Кодировка и версия Java для компиляции
    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = JAVA_VERSION.asInt()
    }

    // Отключаем генерацию метаданных модулей
    tasks.withType(GenerateModuleMetadata).configureEach {
        enabled = false
    }
}
