# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.warning.mode=none

# Project
project_name=Plantopia

# Mod
mod_id=plantopia
mod_version=0.0.1-SNAPSHOT
mod_group_id=by.langvest.plantopia
mod_archives_base_name=Plantopia
mod_name=Plantopia
mod_description=Improves wild nature in the game by adding new biomes, plants, trees and more.
mod_author=LanGvest
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/plantopia
mod_issues=https://github.com/LanGvest/Plantopia/issues
mod_source=https://github.com/LanGvest/Plantopia
mod_license=All Rights Reserved

# Datagen
datagen_package=by.langvest.plantopia.neoforge.datagen
datagen_handler=by.langvest.plantopia.neoforge.handler.PlantopiaDataGenerationHandler

# Java
java_version=17

# Minecraft
minecraft_version=1.20.2
minecraft_version_range=[1.20.2,1.21)

# SpongePowered
spongepowered_gradle_version=0.2.1-SNAPSHOT

# Fabric
fabric_version=0.91.6+1.20.2
fabric_loader_version=0.15.0
fabric_gradle_version=1.2-SNAPSHOT

# NeoForge
neoforge_version=20.2.93
neoforge_version_range=[20.2,)
neoforge_loader_version_range=[1,)
neoforge_gradle_version=7.0.124

# Forge
forge_version=48.1.0
forge_version_range=[48.1,)
forge_loader_version_range=[48,)
forge_gradle_version=6.+

# Mixin
mixin_version=0.8.5
mixin_gradle_version=0.7-SNAPSHOT

# Parchment
parchment_version=2023.12.10
parchment_gradle_version=1.+

# Dependencies
terrablender_version=3.2.0.14
terrablender_version_range=[3.2.0.14,)
findbugs_version=3.0.2
