# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.warning.mode=none

# Project
project_name=Plantopia

# Mod
mod_id=plantopia
mod_version=0.0.1-SNAPSHOT
mod_group_id=by.langvest.plantopia
mod_archives_base_name=Plantopia
mod_name=Plantopia
mod_description=Improves wild nature in the game by adding new biomes, plants, trees and more.
mod_author=LanGvest
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/plantopia
mod_issues=https://github.com/LanGvest/Plantopia/issues
mod_source=https://github.com/LanGvest/Plantopia
mod_license=All Rights Reserved

# Data
data_package=by.langvest.plantopia.datagen
data_handler=by.langvest.plantopia.handler.PlantopiaDataGenerationHandler

# Java
java_version=17

# Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

# Forge
forge_version=47.4.0
forge_version_range=[47,)
forge_loader_version_range=[47,)
forge_gradle_version=6.+

# Mixin
mixin_processor_version=0.8.5
mixin_gradle_version=0.7-SNAPSHOT

# Parchment
parchment_channel=parchment
parchment_version=2023.09.03-1.20.1
parchment_gradle_version=1.+
