modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${mod_issues}"

[[mods]]
	modId = "plantopia"
	version = "${mod_version}"
	displayName = "${mod_name}"
	description = "${mod_description}"
	displayURL = "${mod_homepage}"
	authors = "${mod_author}"
	logoFile = "logo.png"

[[dependencies.plantopia]]
	modId = "forge"
	mandatory = true
	versionRange = "${forge_version_range}"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.plantopia]]
	modId = "minecraft"
	mandatory = true
	versionRange = "${minecraft_version_range}"
	ordering = "NONE"
	side = "BOTH"