modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${mod_issues}"

[[mods]]
    modId = "plantopia"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = "${mod_description}"
    displayURL = "${mod_homepage}"
    authors = "${mod_author}"
    logoFile = "logo.png"

[[mixins]]
    config = "${mod_id}.mixins.json"
    requiredMods = ["plantopia"]

[[mixins]]
    config = "${mod_id}.neoforge.mixins.json"
    requiredMods = ["plantopia"]

[[dependencies.plantopia]]
    modId = "terrablender"
    mandatory = true
    versionRange = "${terrablender_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.plantopia]]
    modId = "neoforge"
    mandatory = true
    versionRange = "${neoforge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.plantopia]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
